### ISSUE TITLE
Green screen issues

### ISSUE THREAD

**Issue by SkyLynn** [HelgeApps/background_video_recorder_faq#3]
HELP!!! When playing back the screen is green and sound is faint.

![Gallery_1706711385705](https://github.com/HelgeApps/background_video_recorder_faq/assets/41308411/7ab307d8-04ae-4e97-a5f8-6761624ce4da)

**Comment by HelgeApps** [comment]
@SkyLynn hi. which device do you use? also try to play in different player, if you enabled HEVC option previously (at the App/Settings/Video), try to disable it as well

**Comment by SkyLynn** [comment]
Either my android tablet or android phone

**Comment by HelgeApps** [comment]
model name? hevc option enabled? can't reproduce the issue, and again - please try to play records in another video player app

**Comment by HelgeApps** [comment]
no feedback
