### ISSUE TITLE
Recording from another app

### ISSUE THREAD

**Issue by Sawyer007** [HelgeApps/background_video_recorder_faq#4]
It doesnt work anymore in the latest version.

Android 14 and tasker.

**Comment by HelgeApps** [comment]
Android 14 doesn't allow to start a foreground service which uses camera or mic from background anymore or another foreground service (which Tasker creates), you can only do it from visible screen (activity) or from widgets.
Later the app will have a foreground service to listen to volume buttons to start/stop recording

**Comment by HelgeApps** [comment]
p.s. the app still targets Android 13 though
so you can use
`com.helgeapps.backgroundvideorecorder.START_RECORDING`
instead of `com.helge.backgroundvideorecorder.START_RECORDING` (screenshots were not updated yet)
to fix it
